config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("home/", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("my_task.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("my_task.home.urls")),
    path("authentic/", include("my_task.send_mail_user.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

my_task/home/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt import views as jwt_views
from . import views as v
from .api import views as va

router_ = routers.DefaultRouter()
app_name = "home"

user_list = va.UserViewSet.as_view({
    'get': 'list'
})
user_detail = va.UserViewSet.as_view({
    'get': 'retrieve'
})

product_list = va.ProductViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
product_detail = va.ProductViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

categories_list = va.CategoryViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
category_detail = va.CategoryViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

product_item_list = va.ProductItemViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

product_item_detail = va.ProductItemViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

order_list = va.OrderViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

order_detail = va.OrderViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

transaction_detail = va.TransactionViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})

transaction_list = va.TransactionViewSet.as_view({'get': 'list', 'post': 'create'})

urlpatterns = [
    path("", v.home, name="home"),
    path("search_product/", v.search_product, name='search_product'),
    path("product_detail/<slug:slug>/", v.detail, name="detail"),
    path("category/<slug:slug>/", v.category_detail, name="category"),
    path("add_to_cart/<slug:slug>", v.add_to_cart, name="add_to_cart"),
    path("delete_product/<int:id_>", v.delete_product, name="delete_product"),
    path("change_quantity/<int:id_>", v.change_quantity, name="change_quantity"),
    path("carts/", v.carts, name="carts"),
    path("check_out/", v.get_form_check_out, name="check_out"),
    path("invoice/", v.invoice, name="invoice"),
    path("invoice_detail/<int:id_trans>/", v.show_invoice, name="invoice_detail"),
]
urlpatterns += [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('hello/', v.HelloView.as_view(), name='hello'),

    path('root/', va.api_root),
    path('api/', include(router_.urls)),
    path('category_list/', categories_list, name='api_category_list'),
    path('category_detail/<int:pk>/', category_detail, name='api_category_detail'),
    path('product_list/', product_list, name='api_product_list'),
    path('product_detail_api/<int:pk>/', product_detail, name='api_product_detail'),
    path('user_list/', user_list, name='api_user_list'),
    path('user_detail/<int:pk>/', user_detail, name='api_user_detail'),
    # path('product_detail/<int:pk>', product_detail, name='api_product_detail'),
    path('product_item_list/', product_item_list, name='api_product_item_list'),
    path('product_item_detail/<int:pk>', product_item_detail, name='api_product_item_detail'),
    path('order_list/', order_list, name='api_order_list'),
    path('order_detail/<int:pk>', order_detail, name='api_order_detail'),
    path('transaction_list/', transaction_list, name='api_transaction_list'),
    path('transaction_detail/<int:pk>', transaction_detail, name='api_transaction_detail'),
]

my_task/send_mail_user/urls.py
from django.urls import path

from .views import LoginView, LogoutView, RegistrationView, VerificationView

app_name = "send_mail_user"
urlpatterns = [
    path("register/", RegistrationView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('activate/<uidb64>/<token>',
         VerificationView.as_view(), name='activate'),
]

my_task/users/urls.py
from django.urls import path

from my_task.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

my_task/home_api/models.py
from django.db import models

# Create your models here.

my_task/send_mail_user/models.py
# from django.db import models

# Create your models here.

my_task/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

my_task/home/api/views.py
from django.contrib.auth import get_user_model

from rest_framework.reverse import reverse
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import (UserSerializer, CategorySerializer, ProductSerializer, ProductItemSerializer, OrderSerializer,
                          TransactionSerializer)
from ..models import Category, Product, ProductItem, Order, Transaction

User = get_user_model()


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """

    def throttled(self, request, wait):
        return super().throttled(request, wait)

    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)

    queryset = User.objects.all()
    serializer_class = UserSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    # permission_classes = [permissions.IsAuthenticatedOrReadOnly,
    #                       IsOwnerOrReadOnly]


class ProductItemViewSet(viewsets.ModelViewSet):
    queryset = ProductItem.objects.all()
    serializer_class = ProductItemSerializer

    def perform_create(self, serializer):
        order, created = Order.objects.get_or_create(user=self.request.user, completed=False)
        order.save()
        serializer.save(order=order)


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer


class TransactionViewSet(viewsets.ModelViewSet):
    queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer

    def perform_create(self, serializer):
        order = Order.objects.get(user=self.request.user, completed=False)
        sum_price = Order.payment(user=self.request.user)
        serializer.save(user=self.request.user, order=order, payment=sum_price)
        order.completed = True
        order.save()


@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'product-list': reverse('home:api_product_list', request=request, format=format),
        'transaction-list': reverse('home:api_transaction_list', request=request, format=format),

        'users-list': reverse('home:api_user_list', request=request, format=format)
    })

my_task/home/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from .models import Category, Order, Product, ProductItem, Transaction

# Create your views here.
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated


class HelloView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self):
        content = {'message': 'Hello, World!'}
        return Response(content)


def home(request):
    products = Product.objects.all()
    # # print('quality', quality)
    context = {
        "products": products
    }
    return render(request, "home/index.html", context)


def search_product(request):
    text_search = request.GET.get('search')
    products = Product.objects.filter(name__contains=text_search.strip())
    if text_search == '':
        messages.error(request, 'The search is not empty')
        return redirect("home:home")
    # print('search_text', products)
    context = {
        'products': products
    }
    return render(request, "home/search_result.html", context)


def detail(request, slug):
    product_detail = get_object_or_404(Product, slug=slug)
    context = {
        "p": product_detail,
    }
    return render(request, "home/product_detail.html", context)


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = category.products.all()
    context = {"products": products}
    return render(request, "home/category.html", context)


def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(user=request.user, completed=False)
        order.save()
        item, create = ProductItem.objects.get_or_create(product=product, order=order)
        # print('created', create)
        if create:
            item.quantity = 1
            item.save()
        else:
            item.quantity += 1
            item.save()
        return redirect("home:detail", slug=product.slug)
        # return HttpResponseRedirect("")

    else:
        return redirect("send_mail_user:login")


@login_required(login_url='send_mail_user:login')
def carts(request):
    order = Order.objects.filter(user=request.user, completed=False).first()
    if order is not None:
        pass
    else:
        return render(request, "home/cart_404.html", context=None)
    product_items = order.product_items.all()
    sum_price = Order.payment(user=request.user)
    context = {"product_items": product_items, "sum_price": sum_price}
    return render(request, "home/carts.html", context)


def delete_product(request, id_):
    item = ProductItem.objects.get(pk=id_)
    if request.user.has_perm("home.delete_productitem"):
        item.delete()
    return redirect("home:carts")


@login_required(login_url='send_mail_user:login')
def change_quantity(request, id_):
    item = ProductItem.objects.get(pk=id_)
    quantity = request.POST.get('quantity')
    if request.user.has_perm("home.change_productitem"):
        item.quantity = quantity
        item.save()
    return redirect("home:carts")


@login_required(login_url='send_mail_user:login')
def get_form_check_out(request):
    return render(request, "home/check_out.html", context=None)


@login_required(login_url='send_mail_user:login')
def invoice(request):
    try:
        order = Order.objects.get(user=request.user, completed=False)
        sum_price = Order.payment(user=request.user)
        transaction, created = Transaction.objects.get_or_create(
            user=request.user, order=order, payment=sum_price
        )
        transaction.save()
        order.completed = True
        order.save()

        for item in order.product_items.all():
            product = Product.objects.get(product_items=item)
            product.in_stock -= item.quantity
            product.save()

        context = {
            'transaction': transaction,
            'sum_price': sum_price,
        }
        return render(request, "home/invoice.html", context=context)
    except Order.DoesNotExist:
        transactions = Transaction.objects.filter(user=request.user)
        return render(request, "home/list_invoice.html", context={'transactions': transactions})


@login_required(login_url='send_mail_user:login')
def show_invoice(request, id_trans):
    transaction = get_object_or_404(Transaction, pk=id_trans)

    context = {
        'transaction': transaction
    }
    return render(request, "home/invoice.html", context=context)

my_task/home_api/views.py
from django.shortcuts import render

# Create your views here.

my_task/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

my_task/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

my_task/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}My task{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="ngocnhi">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet" type="text/css">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
      <a class="navbar-brand" href="{% url 'home:home' %}">E</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Category
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for categogy in categories %}
                <a class="dropdown-item" href="{% url 'home:category' categogy.slug %}">{{ categogy.name }}</a>
              {% endfor %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Support</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">About</a>
          </li>
        </ul>
        <form action="{% url 'home:search_product' %}" class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <div class="dropdown" style="padding-left: 10px">
          {% if request.user.is_authenticated %}
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello {{ request.user.username }}
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">My profile</a>
            <a class="dropdown-item" href="{% url 'send_mail_user:logout' %}">Log Out</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
          <a href="{% url 'home:carts' %}"><button class="btn btn-secondary" type="button" aria-haspopup="true" aria-expanded="false">
            <span style="background-color: red; border-radius: 10px; padding: 3px">{{ request.user.calculator_quality_order }}</span>
            <i class="fas fa-cart-plus"></i>
          </button></a>
          {% else %}
            <a class="btn btn-secondary" href="{% url 'send_mail_user:login' %}">Log In</a>

          <a href=""><button class="btn btn-secondary" type="button" aria-haspopup="true" aria-expanded="false">
            <span style="background-color: red; border-radius: 10px; padding: 3px">0</span>
            <i class="fas fa-cart-plus"></i>
          </button></a>
           {% endif %}
        </div>
      </div>
    </nav>

    <div class="container" style="padding-top: 70px;">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
          {% endfor %}
      {% endif %}

      {% block content %}{% endblock content %}

    </div> <!-- /container -->
    {% include 'pages/footer.html' %}


    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>